version: '3.6'
services:
  pet-database:
    image: 'postgres'
    container_name: 'pet-database'
    env_file:
      - ./.env
    volumes:
      - ./var/pet-database-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pet-database-admin'
    env_file:
      - ./.env
    links:
      - pet-database
    depends_on:
      - pet-database
    volumes:
      - ./var/pet-pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
